resources:
  - dotnet-repo-pvc.yaml
  - gitlab-runner.helm.rendered.template

patches:
- target:
    kind: Deployment
    name: gitlab-runner-gitlab-runner
    labelSelector: "type=deployment"
  path: dotnet-pvc-jsonpatch.yaml